### ISSUE TITLE
Not handling methods terminated with semicolon

### ISSUE THREAD

**Issue by briggySmalls** [tokopedia/gripmock#10]
Hi. First off thanks for your tool.

I had a service defined using the `rpc` syntax terminated with a colon, as introduced in the [protocol buffers documentation](https://developers.google.com/protocol-buffers/docs/proto3#services):

```protobuf
// my-proto.proto
...
service SearchService {
  rpc Search (SearchRequest) returns (SearchResponse);
}
...
```

Which gives rise to the error:
```bash
2019/04/08 18:40:31 can't parse proto <source>:2:59: unexpected ";" (expected "{" ...)
```

This error goes away when using the alternate syntax (terminating an `rpc` definition with curly brackets):

```protobuf
// my-proto.proto
...
service SearchService {
  rpc Search (SearchRequest) returns (SearchResponse) {}
}
...
```

I was pretty confused because I'd never come across the curly brackets syntax before.

**Comment by jekiapp** [comment]
it's funny that I never come across the `;` termination before :smile:. I'm working on it

**Comment by jekiapp** [comment]
should be worked now
