### ISSUE TITLE
How to work with 100+ proto files?

### ISSUE THREAD

**Issue by VladStatnyk** [tokopedia/gripmock#106]
Hi there,

We have so much separate proto files inside project. Can we somehow add them all together? Currently, I successfully run such command:
`docker run -p 4770:4770 -p 4771:4771 -v C:\Git\SomeRepo\src\Protobuf\:/proto tkpd/gripmock:v1.11-beta --imports="/protobuf,/proto" /proto/some_service.proto /proto/SomeServiceMessages/some_service_request.proto /proto/SomeService/some_service_response.proto` 

But, can I register all proto's inside SomeServiceMessages folder, without mentioning them? It's could be more that 100 protos...

Thanks

**Comment by jekiapp** [comment]
Interesting, but since `protoc` is not that "smart" enough to know which files you actually need I can say neither do gripmock. Let's have a thought experiment, if we greedily import all files with .proto files, do we have any gotchas?

**Comment by VladStatnyk** [comment]
Looks like it's working, even for a lot of files.
Thanks!
