### ISSUE TITLE
Note handling protobufs that import other protobufs

### ISSUE THREAD

**Issue by briggySmalls** [tokopedia/gripmock#11]
If a protobuf imports another protobuf, like:

```protobuf
// a.proto
syntax = "proto3";

package a;

import "b.proto";

service A {
    rpc funA(b.BRequest) returns (b.BResponse) {}
}
```

```protobuf
// b.proto

syntax = "proto3";

package b;

message BRequest {
}

message BResponse {
}
```

gripmock fails with:

```bash
can't parse proto <source>:3:25: unexpected "." (expected ")" ...)
```

**Comment by jekiapp** [comment]
It's duplicate with #9 it's pretty hard to implement since I had to resolve all the imported package manually

**Comment by jekiapp** [comment]
Just pushed image `ahmadmuzakki/gripmock:0.4` can you pull and try

**Comment by briggySmalls** [comment]
Hey. Thanks for your work.

I just tried it out and I still get the same error.

```bash
$ cat test_protos/a.proto
syntax = "proto3";

package a;

import "b.proto";

service A {
    rpc funA(b.BRequest) returns (b.BResponse) {}
}

$ cat test_protos/b.proto
syntax = "proto3";

package b;

message BRequest {
}

message BResponse {
}

$ docker run --rm -p 4770:4770 -p 4771:4771 -v (pwd)/test_protos:/proto ahmadmuzakki/gripmock:0.4 gripmock /proto/a.proto
Starting GripMock
Serving stub admin on http://:4771
2019/05/06 20:37:59 can't parse proto <source>:2:15: unexpected "." (expected ")" ...)
```

**Comment by SachinHg** [comment]
hey @jekiapp any progress on this issue? I am hitting the same issue as well.
Thanks

**Comment by jekiapp** [comment]
please also specify all needed proto as parameters in gripmock. in your case should be `gripmock /proto/a.proto /proto/b.proto`

**Comment by jekiapp** [comment]
I'm working on it, sorry for the delay

**Comment by jekiapp** [comment]
hey @briggySmalls, can you show me how to execute protoc with all those files in your locals?

**Comment by jekiapp** [comment]
It seems like you need compile each .proto before it can be used. Its more complicated than just the parsing job. also since the server written in go, the proto file should also has declaration `go_package` before it can be used properly

**Comment by jekiapp** [comment]
PR number #28 solve this issue with [example](https://github.com/tokopedia/gripmock/blob/master/example/multi-package/hello.proto)

**Comment by briggySmalls** [comment]
Sorry I missed your message. Thanks for your work on this issue 🙌
