### ISSUE TITLE
Add Guidelines for using repeated fields

### ISSUE THREAD

**Issue by bhanuone** [tokopedia/gripmock#33]
I have been trying to stub a response which has repeated field of another message. But couldn't make it work. Please add some guidelines for using repeated fields. If it's not supported please add a note in the README about that.

**Comment by jekiapp** [comment]
can you give example of repeated fields?

**Comment by bhanuone** [comment]
I am stubbing using static files. This is my proto file
```protobuf
syntax="proto3";

package com.test_package;

service MyService {
    rpc MyRpc (Request) returns (Response);
}

message Request {
    string request = 1;
}

message Response {
    string response = 1;
    repeated ComplexResponse field_repeated = 2;
    ComplexResponse complex_response = 3;
}

message ComplexResponse {
    string status = 1;
}
```
Here is the json stub
```
{
    "service": "MyService",
    "method": "MyRpc",
    "input": {
        "equals": {
            "request": "Bhanu"
        }
    },
    "output": {
        "data": {
            "response": "My response",
            "simple_repeated": [
                {
                    "status": "200"
                },
                {
                    "status": "200"
                }
            ],
            "ComplexResponse": {
                "status": "200"
            }
        }
    }
}
```

I was getting correct values for `response` and `complex_response` fields. But for `field_repeated` I am always getting empty array as value no matter how I define the value in the stub file

**Comment by bhanuone** [comment]
The issue was not  because of the repeated field. But because of how we define our keys for output in json files. you either have to use camelCase  or PascalCase for multiword keys in output json. And the same does not apply to the input, you always have to use snake_case. There is a lack of consistency between input and output definitions in json stub files. @jekiapp
