### ISSUE TITLE
Problem with running multi proto setup on Docker

### ISSUE THREAD

**Issue by ekedziora** [tokopedia/gripmock#42]
Hi!

I have a problem with running multi proto setup. I try to execute [multi-package](https://github.com/tokopedia/gripmock/tree/master/example/multi-package) example with Docker command:
`docker run --rm -p 4770:4770 -p 4771:4771 -v <local_protos>:/proto tkpd/gripmock --imports=/proto/ /proto/foo.proto /proto/hello.proto`
where _<local_protos>_ is a path to folder containing `hello.proto`, `foo.proto` and `bar/bar.proto` as in example. As a result container doesn't start and I get following logs:

```
Starting GripMock
Serving stub admin on http://:4771
2020/02/28 20:36:20 Failed to generate server formatting: 35:62: expected type, found '.' (and 2 more errors)
// Code generated by GripMock. DO NOT EDIT.
package main

import (
        "bytes"
        "encoding/json"
        "fmt"
        "io"
        "io/ioutil"
        "log"
        "net"
        "net/http"

        "github.com/mitchellh/mapstructure"
        "golang.org/x/net/context"
        "google.golang.org/grpc"
        "google.golang.org/grpc/reflection"
)

import bar "github.com/tokopedia/gripmock/example/multi-package/bar"

const (
        TCP_ADDRESS  = ":4770"
        HTTP_PORT = ":4771"
)



type Gripmock struct{}





func (s *Gripmock) Greet(ctx context.Context, in *bar.Bar) (*.Response,error){
        out := &.Response{}
        err := findStub("Gripmock", "Greet", in, out)
        return out, err
}







func main() {
        lis, err := net.Listen("tcp", TCP_ADDRESS)
        if err != nil {
                log.Fatalf("failed to listen: %v", err)
        }

        s := grpc.NewServer()


        RegisterGripmockServer(s, &Gripmock{})



        reflection.Register(s)
        fmt.Println("Serving gRPC on tcp://" + TCP_ADDRESS)
        if err := s.Serve(lis); err != nil {
                log.Fatalf("failed to serve: %v", err)
        }
}


type payload struct {
        Service string      `json:"service"`
        Method  string      `json:"method"`
        Data    interface{} `json:"data"`
}

type response struct {
        Data  interface{} `json:"data"`
        Error string      `json:"error"`
}

func findStub(service, method string, in, out interface{}) error {
        url := fmt.Sprintf("http://localhost%s/find", HTTP_PORT)
        pyl := payload{
                Service: service,
                Method:  method,
                Data:    in,
        }
        byt, err := json.Marshal(pyl)
        if err != nil {
                return err
        }
        reader := bytes.NewReader(byt)
        resp, err := http.DefaultClient.Post(url, "application/json", reader)
        if err != nil {
                return fmt.Errorf("Error request to stub server %v",err)
        }

        if resp.StatusCode != http.StatusOK {
                body, _ := ioutil.ReadAll(resp.Body)
                return fmt.Errorf(string(body))
        }

        respRPC := new(response)
        err = json.NewDecoder(resp.Body).Decode(respRPC)
        if err != nil {
                return fmt.Errorf("decoding json response %v",err)
        }

        if respRPC.Error != "" {
                return fmt.Errorf(respRPC.Error)
        }

        return mapstructure.Decode(respRPC.Data, out)
}

--gripmock_out: protoc-gen-gripmock: Plugin failed with status code 1.
2020/02/28 20:36:20 Fail on protoc exit status 1
```

Additionally when I try to run another setup with two different and not related proto files I get another error:

```
Starting GripMock
Serving stub admin on http://:4771
2020/02/28 20:54:56 Failed to generate server formatting: 65:7: expected 'IDENT', found 'struct'
// Code generated by GripMock. DO NOT EDIT.
package main

import (
        "bytes"
        "encoding/json"
        "fmt"
        "io"
        "io/ioutil"
        "log"
        "net"
        "net/http"

        "github.com/mitchellh/mapstructure"
        "golang.org/x/net/context"
        "google.golang.org/grpc"
        "google.golang.org/grpc/reflection"
)

const (
        TCP_ADDRESS  = ":4770"
        HTTP_PORT = ":4771"
)



type MathService struct{}





func (s *MathService) Add(ctx context.Context, in *Double) (*Result,error){
        out := &Result{}
        err := findStub("MathService", "Add", in, out)
        return out, err
}





func (s *MathService) Power(ctx context.Context, in *Single) (*Result,error){
        out := &Result{}
        err := findStub("MathService", "Power", in, out)
        return out, err
}





func (s *MathService) Hello(ctx context.Context, in *Text) (*Text,error){
        out := &Text{}
        err := findStub("MathService", "Hello", in, out)
        return out, err
}







type  struct{}







func main() {
        lis, err := net.Listen("tcp", TCP_ADDRESS)
        if err != nil {
                log.Fatalf("failed to listen: %v", err)
        }

        s := grpc.NewServer()


        RegisterMathServiceServer(s, &MathService{})



        RegisterServer(s, &{})



        reflection.Register(s)
        fmt.Println("Serving gRPC on tcp://" + TCP_ADDRESS)
        if err := s.Serve(lis); err != nil {
                log.Fatalf("failed to serve: %v", err)
        }
}


type payload struct {
        Service string      `json:"service"`
        Method  string      `json:"method"`
        Data    interface{} `json:"data"`
}

type response struct {
        Data  interface{} `json:"data"`
        Error string      `json:"error"`
}

func findStub(service, method string, in, out interface{}) error {
        url := fmt.Sprintf("http://localhost%s/find", HTTP_PORT)
        pyl := payload{
                Service: service,
                Method:  method,
                Data:    in,
        }
        byt, err := json.Marshal(pyl)
        if err != nil {
                return err
        }
        reader := bytes.NewReader(byt)
        resp, err := http.DefaultClient.Post(url, "application/json", reader)
        if err != nil {
                return fmt.Errorf("Error request to stub server %v",err)
        }

        if resp.StatusCode != http.StatusOK {
                body, _ := ioutil.ReadAll(resp.Body)
                return fmt.Errorf(string(body))
        }

        respRPC := new(response)
        err = json.NewDecoder(resp.Body).Decode(respRPC)
        if err != nil {
                return fmt.Errorf("decoding json response %v",err)
        }

        if respRPC.Error != "" {
                return fmt.Errorf(respRPC.Error)
        }

        return mapstructure.Decode(respRPC.Data, out)
}

--gripmock_out: protoc-gen-gripmock: Plugin failed with status code 1.
2020/02/28 20:54:56 Fail on protoc exit status 1
```

I tried with different Docker image tags available but no luck.
Am I missing something here? I would really appreciate any help.

**Comment by treethought** [comment]
getting the same issue

**Comment by jekiapp** [comment]
Did you guys check this [file](https://github.com/tokopedia/gripmock/blob/master/example/multi-package/entrypoint.sh)? 

@ekedziora the first error log caused by this syntax error `*.Response` that should be `*bar.Response`, but I haven't reproduce on how that code generated to be like that
the second error log definitely missing Service declaration here `type  struct{}`
did you ever succeeded try gripmock with single proto pacakge?

**Comment by jekiapp** [comment]
I'm able to reproduce the error, checking it.

**Comment by jekiapp** [comment]
Just rebuilt and pushed the image, Please remove local image and pull the `latest` version. 

I tried with 
```
docker run --rm -p 4770:4770 -p 4771:4771 -v $GOPATH/src/github.com/tokopedia/gripmock/example/multi-package/:/proto/ tkpd/gripmock:latest --imports=/proto --stub=/proto/stub /proto/foo.proto /proto/hello.proto
```
and it's running fine, Please check.

ps: $GOPATH is the root path of golang codes, please adjust accordingly

**Comment by bcatarino** [comment]
I'm still having this error, and the proposed solution is not working for me. I'm calling it with:

`docker run --rm -p 4770:4770 -p 4771:4771 -v <myrootfolder>:/proto tkpd/gripmock:latest --imports=/proto /proto/evaluator_api.proto`

and I get 

> thirdparty/validator/validator.proto: File not found.
> evaluator/v1beta2/evaluator.proto: File not found.
> evaluator/v1beta2/subject.proto: File not found.
> evaluator_api.proto: Import "thirdparty/validator/validator.proto" was not found or had errors.
> evaluator_api.proto: Import "evaluator/v1beta2/evaluator.proto" was not found or had errors.
> evaluator_api.proto: Import "evaluator/v1beta2/subject.proto" was not found or had errors.

Evaluator and Subject are in the same folder, so it should find at least those. I don't own the code, so I can't just change the package names. 

I did try to hack it and put it all in the same folder, and run it with all the files specified in the example:
`docker run --rm -p 4770:4770 -p 4771:4771 -v <myrootfolder>:/proto tkpd/gripmock:latest --imports=/proto /proto/descriptor.proto /proto/validator.proto /proto/subject.proto /proto/evaluator.proto /proto/evaluator_api.proto`

In which case I get

> google/protobuf/descriptor.proto: File not found.
> validator.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
> validator.proto:18:8: "google.protobuf.FieldOptions" seems to be defined in "descriptor.proto", which is not imported by "validator.proto".  To use it here, please add the necessary import.
> validator.proto:22:8: "google.protobuf.OneofOptions" seems to be defined in "descriptor.proto", which is not imported by "validator.proto".  To use it here, please add the necessary import.

Any ideas how to fix this, or is it not support atm? Thanks!

**Comment by jekiapp** [comment]
@bcatarino I don't your issue is the same with the one mentioned above. original issue is that gripmock fail to generate grpc server based on proto.

Your first issue definetely about path issue. `<myrootfolder>` should be pointing to a folder that contain `thirdparty` and `evaluator` folders. you could debug that with `docker run -v <myrootfolder>:/proto --entrypoint=/bin/sh -it tkpd/gripmock:latest ` and check your files. 

Your second issue it's supported in gripmock, all you need to do is `--imports="/protobuf,/proto"`. I will make `/protobuf` always imported in next iteration, at this point it will be replaced if one specify `import` clause.

**Comment by ekedziora** [comment]
Thank you @jekiapp, after pulling latest image everything seems to work fine for my scenario. From my perspective the issue can be closed.

**Comment by andruhon** [comment]
Just a note.

To get it working I had to point to `tkpd/gripmock:0.8.2` rather than to `tkpd/gripmock:latest`. It turns like latest on dockerhub is older than 0.8.2. Also tag on github showing 1.8.2 and dockerhub showing 0.8.2
