### ISSUE TITLE
Gripmock is unable to bind data if the response message has "_" in one of the field name

### ISSUE THREAD

**Issue by h3masood** [tokopedia/gripmock#46]
I am trying to setup a mock service with response messages that have properties with "_" in their name. However, for these messages gripmock is returning responses without binding what I have put in the "data" property in my stubs for the said properties. For example, if using the following protos

`service Gripmock {
    rpc SayHello (Request) returns (Response);
}
`
`message Request {
  string name = 1;
}
`
`message Response {
   string message_field = 1;
}`

along with this stub
`{
    "service": "Gripmock",
    "method": "SayHello",
    "input": {
        "equals": {
            "name": "Gripmock"
        }
    },
    "output": {
        "data": {
        	"message_property": "Hello from gripmock"
        }
    }
}`

the returned response has an empty string in the 'message_property' versus "Hello from gripmock". Also, there are no logs warning me about if something's gone wrong. Are properties with "_" in their names not supported? Or is this a bug?

**Comment by jekiapp** [comment]
PR #52 merged
