### ISSUE TITLE
Gripmock container fails to build when using protobuf definitions split across multiple files

### ISSUE THREAD

**Issue by h3masood** [tokopedia/gripmock#47]
I am trying to mock a service that has protobuf definitions split across multiple files. However, gripmock throws an error saying either my imports (think file1.proto importing file2.proto) were either not found or or had errors. I know that they don't have any errors because gripmock runs fine when I copy the definitions in file2.proto over to file1.proto. Is multi-file protobuf definitions not supported yet? If it is can you please update your docs to reflect how I can work with them?

**Comment by carvalhorr** [comment]
I had the same issue when evaluating gripmock. All my services are defined in multiple proto files. I ended up developing something for what I needed, but I am interested to see the solution for this issue.

**Comment by ChrisVanBael** [comment]
I'm struggling with the same issue. 
The multi-package example seems to indicate imports can be done, but I haven't figured out how.
An example would be greatly appreciated! Thanks.

**Comment by jekiapp** [comment]
Hi guys sorry for late reply, did you check examples in this folder? https://github.com/tokopedia/gripmock/tree/master/example/multi-package

**Comment by jekiapp** [comment]
is it related with issue #50 ?

**Comment by jekiapp** [comment]
duplicate with #50

**Comment by jekiapp** [comment]
I just built tkpd/0.8.2 docker image with patch from #45 and #52 please pull and try it.
