### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by J7mbo** [tokopedia/gripmock#48]
docker-compose:

```
  gripmock:
    image: tkpd/gripmock:0.8
    ports:
      - "4770:4770"
      - "4771:4771"
```

Error:

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
        /go/src/github.com/tokopedia/gripmock/gripmock.go:25 +0xc36
```

This is also with mounting a single .proto file in /protos.

**Comment by mpankiewicz97** [comment]
Hi, could you please share what was the issue?

**Comment by nirdunetz** [comment]
@J7mbo solution?

**Comment by dan-r95** [comment]
The missing part is the mounted volume like so:
```
volumes:
   - <src>:<destination> 
```

**Comment by J7mbo** [comment]
Sorry, I don't even remember using this 😅 I hope you solved it (and apologies for being one of those annoying people who just closes an issue without sharing the solution - don't be like me here!!)
