### ISSUE TITLE
How to stub both gRPC and Rest (GET/POST) endpoint?

### ISSUE THREAD

**Issue by harshmah** [tokopedia/gripmock#55]
I have a service that is based on gRPC. But that having both types of downstream:

Web Server - Call them via GET/POST.
gRPC Server - Call them via gRPC.
Can we use gripmock to stub both endpoints? If yes, please share an example.

**Comment by jekiapp** [comment]
No gripmock only mock gRPC endpoints. for REST you can use [wiremock](http://wiremock.org/)
