### ISSUE TITLE
Support proto3 canonical encoding

### ISSUE THREAD

**Issue by bjaglin** [tokopedia/gripmock#58]
grimock 1.8.2 fails to parse a response with a `google.protobuf.Timestamp` encoded as a single string, as defined in https://developers.google.com/protocol-buffers/docs/proto3#json:

```
* 'TimestampField' expected a map, got 'string'
```

https://github.com/golang/protobuf/blob/v1.0.0/jsonpb/jsonpb.go should be used instead of `json.Marshal` in:
* https://github.com/tokopedia/gripmock/blob/9315ff9/protoc-gen-gripmock/server.tmpl#L152
* https://github.com/tokopedia/gripmock/blob/9315ff9/protoc-gen-gripmock/server.tmpl#L179

**Comment by jekiapp** [comment]
fixed by #62
