### ISSUE TITLE
Cannot mock response that includes oneOf

### ISSUE THREAD

**Issue by ceramcardle** [tokopedia/gripmock#61]
The example proto file in the docs works fine but when I amend it to include a oneOf it does not work for me.
The amended proto file is:
`syntax = "proto3";

package simple;

// The Gripmock service definition.
service Gripmock {
  // simple unary method
  rpc SayHello (Request) returns (Reply);
}

// The request message containing the user's name.
message Request {
  string name = 1;
}

message Reply {
  oneof replyType {
    Reply1 reply1 = 1;
    Reply2 reply2 = 2;
  }
}

// usual response type
message Reply1 {
  string message = 1;
  int32 return_code = 2;
}

// other response type
message Reply2 {
  int32 other = 1;
}`
When I run my gripmock container I add a dynamic stub as follows:
`curl -X POST -d \
'{  "service":"Gripmock",
    "method":"SayHello",
    "input":{
        "equals":{
            "name":"tokopedia"
        }
    },
    "output":{
        "data":{
            "reply1":{
                "message":"Hello GripMock"
            }
        }
    }
}' localhost:4881/add`
and the stub is added ok

However when I call out to the mocked gRPC service, a match is returned but the serialized data does not include my reply.
The stringified data returned is:
`{"wrappers_":null,"arrayIndexOffset_":-1,"array":[],"pivot_":1.7976931348623157e+308,"convertedPrimitiveFields_":{}}`

Note that I am generating typescript stubs and using those to test.

My key questions are:
1. Has anyone successfuly stubbed a oneOf using gripmock?
2. If so, what is different to what we have done above?

**Comment by jekiapp** [comment]
fixed by #62
