### ISSUE TITLE
Not handling common protobuf message types

### ISSUE THREAD

**Issue by saichander** [tokopedia/gripmock#9]
I have a proto file like this:
```
syntax = "proto3";

option optimize_for = SPEED;

package events_store;

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";

service EventsStore {
    rpc CreateEvent (Event) returns (CreateEventResponse) {}
    rpc GetAllEvents (GetAllEventsRequest) returns (EventsList) {}

    rpc HealthCheck(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}
```
While passing this proto file to gripmock, it was unable to find the file where common protobuf message types like wrappers.proto and empty.proto are defined. I am getting the following error
```
Starting GripMock
Serving stub admin on http://:4771
google/protobuf/wrappers.proto: File not found.
google/protobuf/empty.proto: File not found.
events_store.proto: Import "google/protobuf/wrappers.proto" was not found or had errors.
events_store.proto: Import "google/protobuf/empty.proto" was not found or had errors.
events_store.proto:49:3: "google.protobuf.StringValue" is not defined.
2019/01/11 19:45:42 Fail on protoc exit status 1
```
I got this error while running it on docker image with the command
`docker run -p 4770:4770 -p 4771:4771 -v /events_store:/proto ahmadmuzakki/gripmock gripmock -stub=/proto/stubs /proto/events_store.proto`

When I ran this in my local using protoc version 3.6.1  it was able to parse the file successfully.

**Comment by jekiapp** [comment]
Can you do this? `docker run -p 4770:4770 -p 4771:4771 -v /events_store:/proto ahmadmuzakki/gripmock gripmock -stub=/proto/stubs /proto` (without specifically pointing to events_store.proto) gripmock should read all proto inside the folder

**Comment by saichander** [comment]
@jekiapp I think you are assuming that "google/protobuf/wrappers.proto" file is present in my local folder. It is not, it is present in the `google.protobuf` package. When I import it in my proto file, protoc gets all message types defined in "google/protobuf/wrappers.proto" file from `google.protobuf` package(https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto). 
Also, the command `docker run -p 4770:4770 -p 4771:4771 -v /events_store:/proto ahmadmuzakki/gripmock gripmock -stub=/proto/stubs /proto` is not fetching all the proto files in the folder, it is raising an error `Error on reading proto read /proto: is a directory`.

**Comment by jekiapp** [comment]
apparently you need dependencies from `github.com/google/protobuf`. I'm gonna add the path to be imported when compiling the proto file

**Comment by jekiapp** [comment]
Hmm it's more complicated than I thought, it will take sometimes but I'm trying to figure it out.

**Comment by saichander** [comment]
Take your time. As a workaround, I have downloaded these files in my local and stored with directory structure "google/protobuf/wrappers.proto". It is working now, but providing support for handling these dependencies would be a great addition. Thanks 😄

**Comment by SachinHg** [comment]
Hey @saichander @jekiapp , 
here is my problem. I have a proto which depends on few other protos. They all have the same optional go package like `go_package_name` and reside in the same directory `\protos`.
Running the command `docker run --rm -p 4770:4770 -p 4771:4771 -v (pwd):/protos ahmadmuzakki/gripmock:0.4 gripmock /protos/my.proto` throws the error `can't parse proto <source>:85:26: unexpected "." (expected ")" ...)`.

Is there a solution for this?

**Comment by jekiapp** [comment]
can you put the syntax in line 85

**Comment by jekiapp** [comment]
Hi @saichander I just pushed image `ahmadmuzakki/gripmock:0.7` and use similar example in [hello.proto](https://github.com/tokopedia/gripmock/blob/f8d858e1048f8246e52e9b1af008e2d2b71ad591/example/pb/hello.proto#L19) to represent utilizing WKT
