### ISSUE TITLE
How to use 1.10 without Go

### ISSUE THREAD

**Issue by bklooste** [tokopedia/gripmock#93]
We use C#, Node and Java and was using gripmock as a container but i now get protoc-gen-go: unable to determine Go import path for "cancellation.proto" errors when specifiying more than 1 file .. 

![image](https://user-images.githubusercontent.com/261344/132287930-f51e15a4-f164-4d5e-bd79-f7440f8d9b79.png)

Whats the best way to deal with this ?

**Comment by jekiapp** [comment]
try using `tkpd/gripmock:v1.11-beta` image
