### ISSUE TITLE
[Q] How config go_package?

### ISSUE THREAD

**Issue by shizuku-nem** [tokopedia/gripmock#97]
go_package is required in .proto. I am wondered **what is the rule setting go_package?**

My project structure:
![image](https://user-images.githubusercontent.com/52918894/135224018-b6a66714-8e30-463d-a5f0-b32b95b8c861.png)

I set:
```
option go_package = "github.com/daipthraomng";
```
or
```
option go_package = "github.com/daipthraomng/bookstore-gripmock";
```
Then both are fine. In two cases, mock service can run and interact.
I'm confused about it.

**Comment by jekiapp** [comment]
it's basically a requirement from protoc, if it isn't present, it just stopped generating the files. Since gripmock use protogen-go I need to obliged to that rule, so basically you can put arbitrary stuff there as long it has that format it works fine.
